### ISSUE TITLE
[Bug]: Type coverage shows 100% despite of missing parameter types

### ISSUE THREAD

**Issue by marventhieme** [pestphp/pest#1032]
### What Happened

I run `php artisan test --type-coverage --min=100`.
In the output I see files where missing parameter types/return types are showing. An output per file is e.g. `... pa99, pa118, pa140, pa160, pa180 93%`

But, at the bottom of the report I get `Total: 100.0 %`

Could this be a rounding issue, that my total is e.g. 99,996% and you round up to 100%?

### How to Reproduce

Run `php artisan test --type-coverage --min=100`.
Have ca. 700 files to check and fail one file.

### Pest Version

2.26.0

### PHP Version

8.2.13

### Operation System

macOS

### Notes

"pestphp/pest-plugin-type-coverage": 2.5.0

**Comment by owenvoke** [comment]
Looking at [the code behind this](https://github.com/pestphp/pest-plugin-type-coverage/blob/2.x/src/Result.php#L80), we use `round()` for the total coverage. We should probably use `mode: PHP_ROUND_HALF_DOWN` rather than the default of `PHP_ROUND_HALF_UP`. 🤔 I guess that wouldn't help if the coverage is `99.98%` or something. But, it seems more correct to lower the coverage than raise it.

**Comment by nunomaduro** [comment]
Can you PR that change @owenvoke ?

**Comment by owenvoke** [comment]
Sure (https://github.com/pestphp/pest-plugin-type-coverage/pull/18), this still doesn't fix the underlying issue, where `round()` basically will always round anything above `.5` to the higher number (with a precision of `0`). The only real way around that is to have a precision of `1` or more. But then you end up with a float, and we expect an integer, so we cast it anyway which loses the precision.

**Comment by nunomaduro** [comment]
Fixed: https://github.com/pestphp/pest-plugin-type-coverage/pull/18.
