### ISSUE TITLE
[Bug]: `pest:dusk` command silently removed

### ISSUE THREAD

**Issue by stevebauman** [pestphp/pest#1049]
### What Happened

I've created a composer package called [Laravel Husk](https://github.com/stevebauman/laravel-husk) that involves running Laravel Dusk using Laravel Zero + Pest. This used to work great, until it randomly started failing on all my repositories many months ago (just got around to investigating it now). This package was also reported in [Laravel News](https://laravel-news.com/use-laravel-dusk-to-test-js-based-applications).

These issues point to its existence, as well as a anchor tag to its documentation, yet on the docs site it no longer exists: https://github.com/pestphp/pest/issues/640
https://github.com/pestphp/pest/issues/279

https://pestphp.com/docs/plugins/laravel#laravel-dusk

In this commit, the docs were updated silently with the command removed:

https://github.com/pestphp/docs/commit/d990aa7d34a6c8e395b590d820ac1cc5ac37d002#diff-785e4f28fd1593fc33c2455ee225bc0eb1270f2567c040c93b1d8c77c9579a95L214

What happened to the `pest:dusk` command? Is there any alternative that allows me to run Laravel Dusk tests inside of Laravel Zero?

### How to Reproduce

Try to run `php application pest:dusk`

### Pest Version

2.30.0

### PHP Version

8.1.22

### Operation System

macOS

**Comment by owenvoke** [comment]
The command should still exist as far as I know. 🤔 It's part of the Laravel plugin.
https://github.com/pestphp/pest-plugin-laravel/blob/2.x/src/Commands/PestDuskCommand.php

I think the correct way now to run it, is to just use the `--pest` flag on [the core `dusk` command](https://github.com/laravel/dusk/blob/7.x/src/Console/DuskCommand.php).

Looking at the failing CI runs on your repositories, they seem to be because of `dusk:chrome-driver` failing to download `https://chromedriver.storage.googleapis.com/LATEST_RELEASE_120` (404), not part of Pest?

**Comment by nunomaduro** [comment]
> I think the correct way now to run it, is to just use the --pest flag on [the core dusk command](https://github.com/laravel/dusk/blob/7.x/src/Console/DuskCommand.php).

This.
