### ISSUE TITLE
[Bug]: Cloning from cache can't find commit hash (History rewritten)

### ISSUE THREAD

**Issue by Ssionn** [pestphp/pest#1089]
### What Happened

My friend is trying to install pestphp, the problem is is that it's failing to execute because HEAD is at 5b0f88c release: v2.33.6.

Is this an issue on our side or pest's side?

![image](https://github.com/pestphp/pest/assets/90753599/b3477e4e-fda9-412a-9d68-2af3ebca2fd8)

We've tried doing ```composer update pestphp/pest```, but to no avail.

### How to Reproduce

Install pestphp/pest using composer, it throws an error. try composer update pestphp/pest, throws an error

### Pest Version

It shows as '*'

### PHP Version

8.2.12

### Operation System

Windows

**Comment by owenvoke** [comment]
I'd say, enable the Zip extension so that Composer can download the distribution files. This will mean that the tests aren't included, which will resolve your issue.

The issue is with Windows and the fact that it's cloning the entire repository which contains a path that is too long for Windows (over 256 characters).

Enabling the Zip extension should be the easiest fix, and should speed up Composer installs a lot.
