### ISSUE TITLE
[Bug]: Route will not found if test more than 1 times

### ISSUE THREAD

**Issue by izcream** [pestphp/pest#1140]
### What Happened

when try to test more than 1 http request in same file with same prefix (in my case is /api/v2*) the second test will alway return route not found.

![image](https://github.com/pestphp/pest/assets/10282500/e1a58be7-4284-48a0-a513-1b713a3197c6)
![image](https://github.com/pestphp/pest/assets/10282500/1e49e152-00b2-438b-a8dd-82d09d0f2d40)

But if change route prefix to another like /api/privacy its will fine

![image](https://github.com/pestphp/pest/assets/10282500/88b579a3-42f2-477e-b257-ef97bfba48cc)

### How to Reproduce

Just try to create test with same base route prefix 

### Pest Version

2.34.7

### PHP Version

8.2.18

### Operation System

Linux

### Notes

Laravel version: 10.48.8

**Comment by alsterholm** [comment]
I'm unable to reproduce this. The following is working for me in a newly created Laravel project:

**routes/web.php**
```php
Route::prefix('/api/v2')->group(function () {
    Route::get('/guest/home', fn () => response([], 200));
    Route::get('/ok', fn () => response([], 200));
});
```

**tests/Feature/ExampleTest.php**
```php
it('/api/v2/guest/home route', function () {
    $this->getJson('/api/v2/guest/home')->assertOk();
});

it('/api/v2/ok route', function () {
    $this->getJson('/api/v2/ok')->assertOk();
});
```

Tests are passing when running `php artisan test`.

I think you need to share some more code, or make sure you have registered your routes correctly. You can also try running the test with exception handling disabled, in order to be able to see the exception being thrown (seeing as you're getting a status 500 error that is likely the case).

```php
    $this->withoutExceptionHandling()->getJson('/api/v2/ok')->assertOk();
```

**Comment by izcream** [comment]
Sorry for late reply. I think i found cause of my issues

I use `require_once __DIR__.'/v2/api.php';` in api.php to include my v2 api, and yes its include 1 times so my second test this route will not load😂

Just change it to `require` or use laravel Bootstrap route in Provider then it's will work fine

Thanks for helping❤️
