### ISSUE TITLE
chore: improve feedback on github actions 

### ISSUE THREAD

**Issue by nunomaduro** [pestphp/pest#119]
Would be cool to have somthing like this for pest.

![2020-07-01 11 51 42](https://user-images.githubusercontent.com/5457236/86230493-6b1df980-bb91-11ea-957e-622cac78b8ec.jpg)

**Comment by owenvoke** [comment]
Ha, I was just looking at that PR. 😄 Should be relatively easy to implement.

I know that for this repo, we implemented a ["problem matcher"](https://github.com/pestphp/pest/blob/master/.github/workflows/tests.yml#L47-L48), but a `--github-ci` plugin would be pretty neat. 👍

**Comment by owenvoke** [comment]
I think this would be a change to [the `Style::writeErrorsSummary()` method in Collision](https://github.com/nunomaduro/collision/blob/805929cb4bb6b24ef56a28a4121eb1336803effd/src/Adapters/Phpunit/Style.php#L82).

Something such as appending the following to the end of the method:
```php
// Output errors for GitHub Actions
$this->output->writeln(["::error file={$testResult->throwable->getFile()},line={$testResult->throwable->getLine()}::{$testResult->throwable->getMessage()}"]);
```

Except it needs to be configurable obviously, so that we can pass the option from Pest. 👍

Might have a look at this at some point if I get the chance.

**Comment by nunomaduro** [comment]
I've no plans on working on this. Feel free to submit a pull request.
