### ISSUE TITLE
Release V0.3

### ISSUE THREAD

**Issue by nunomaduro** [pestphp/pest#171]
- [x] Tag all plugins and the core
- [x] core
- [x] pest-plugin-coverage
- [x] pest-plugin
- [x] pest-plugin-faker
- [x] pest-plugin-template
- [x] pest-plugin-watch
- [x] pest-plugin-laravel
- [x] pest-plugin-livewire
- [x] pest-plugin-init
- [x] pest-plugin-global-assertions
- [x] spatie-snapshots
- [x] Pull request upgrade guide to the docs.
- [x] Verify documentation 
- [x] Write blog post

**Comment by owenvoke** [comment]
Looks like for the Livewire plugin it is failing due to a change to the reflection API in PHP 8, as far as I can tell, this should be resolvable by forcing a minimum of [Laravel 7.14 and 6.18.17](https://github.com/laravel/framework/commit/1af06328c77b875dfb3304f3e9611c2078314acb).

- [Livewire Plugin](https://github.com/pestphp/pest-plugin-livewire/blob/master/composer.json)
- [Failing test suite](https://github.com/pestphp/pest-plugin-livewire/runs/1028578572?check_suite_focus=true)
