### ISSUE TITLE
it and depends

### ISSUE THREAD

**Issue by fbraem** [pestphp/pest#213]
When a test created with "it", the depends function doesn't work.

````php
it('can create a converter', function () {
    $factory = new ConverterFactory();
    $factory->register('md', MarkdownConverter::class);
    $converter = $factory->createConverter('md');
    expect($converter)->toBeInstanceOf(MarkdownConverter::class);
    return $converter;
});

it('can convert markdown', function ($converter) {
    $html = $converter->convert('**TEST**');
    expect($html)->toBe('<p><strong>TEST</strong></p>');
})->depends('it can create a converter');
````
This results in the following output:

````
WARN  Tests\Core\Infrastructure\Converter\ConverterFactoryTest
  ✓ it can create a converter
  ! it can convert markdown → This test depends on "P\Tests\Core\Infrastructure\Converter\ConverterFactoryTest::can create a converter" which does not exist.

  Tests:  1 warnings, 1 passed
  Time:   0.24s
````
Leaving "it" out of the testname doesn't work, but adding "it" twice to the testname works:

````php
it('can convert markdown', function ($converter) {
    $html = $converter->convert('**TEST**');
    expect($html)->toBe('<p><strong>TEST</strong></p>');
})->depends('it it can create a converter');
````
````
   PASS  Tests\Core\Infrastructure\Converter\ConverterFactoryTest
  ✓ it can create a converter
  ✓ it can convert markdown

  Tests:  2 passed
  Time:   0.29s
````

**Comment by owenvoke** [comment]
Sorry it's taken so long to reply, I was able to replicate this issue. It looks like this is due to our use of [`ExecutionOrderDependency`](https://github.com/sebastianbergmann/phpunit/blob/master/src/Framework/ExecutionOrderDependency.php#L49) in the [TestCall object](https://github.com/pestphp/pest/blob/d85432933cfd916f691a564ccd10dab82d008dd6/src/PendingObjects/TestCall.php#L98).

The `createFromDependsAnnotation` call splits the string by a space, which allows support for ["clone options"](https://phpunit.readthedocs.io/en/9.3/writing-tests-for-phpunit.html#writing-tests-for-phpunit-test-dependencies).

We should create our own version of this method that doesn't split the call. 👍🏻 Basically just replace the `array_map()` in `TestCall::depends()` with:

```php
$tests = array_map(function (string $test) use ($className): ExecutionOrderDependency {
    if (strpos($test, '::') === false) {
        $test = "{$className}::{$test}";
    }

    return new ExecutionOrderDependency($test, null, '');
}, $tests);
```

I've opened #216 to resolve this issue.
