### ISSUE TITLE
Reusable beforeEach and beforeAll

### ISSUE THREAD

**Issue by albertpratomo** [pestphp/pest#255]
I want to make a Trait that does something in the `beforeAll` of the test.

Is it possible to use the `beforeAll()` function in a trait? And then call `uses(Trait::class)` in the test case? I was having problem with that..

Also I tried to use PHPUnit TestCase methods like `setUp` and `setUpBeforeClass`, but it says that it conflicts with Pest's TestCaseFactory..

**Comment by jordanbrauer** [comment]
@albertpratomo not sure if you have found a workaround for you use case yet, but I have been sharing closures through static constructors, like so (note that this is just sample/pseudo-code and not specific to any framework)

```php
namespace YourApp\Test;

final class Setup
{
    public static function logout(): Closure
    {
        return fn (): void => auth()->logout();
    }

    public static function rollback(): Closure
    {
        return fn (): void => DB::rollback();
    }

    public static function txn(): Closure
    {
        return fn (): void => DB::beginTransaction();
    }
}
```

and used like so

```php
beforeEach(Setup::txn());
afterEach(Setup::rollback());
```

I haven't really needed to in my own project, _yet_, but if you were to need more than one to run, you could easily compose them, and just pass the final closure to `beforeEach`, `beforeAll`, etc.

You could probably even, as an invokable object just autoload the setups you need instead of one with static methods, like so, while maintaining composability since at the core you're just dealing in closures (i.e., callables).

```php
namespace YourApp\Test\Setup;

final class MyFeatureSetup
{
    public function __invoke(): void
    {
        // check & call all the stuff you need to here;
    }
}
```

and then use it like;

```php
beforeEach(new MyFeatureSetup());
```

---

Hope this helps!

**Comment by nunomaduro** [comment]
@jordanbrauer Would be cool to actually have something to allow to configure global beforeBeachs...

```
uses()->beforeEach(fn () => ...)->in('folder');
```

**Comment by jordanbrauer** [comment]
Woah, that would be cool! I guess you would just configure/call that in the `Pest.php` file?

**Comment by nunomaduro** [comment]
Correct. Let me know if you are up to work on it.

**Comment by jordanbrauer** [comment]
> Correct. Let me know if you are up to work on it.

Sure thing, I'll take a crack at it! I'll get started ASAP , likely next weekend.

**Comment by jordanbrauer** [comment]
Worked started in #282. Started with a little PoC with `beforeEach`.

**Comment by nunomaduro** [comment]
Released.
