### ISSUE TITLE
php artisan pest:dusk fails

### ISSUE THREAD

**Issue by pristavu** [pestphp/pest#279]
The "browse" option does not exist.  

(https://github.com/laravel/dusk/pull/870)

**Comment by nunomaduro** [comment]
Can you please elaborate?

**Comment by owenvoke** [comment]
I think they are saying that running `pest:dusk --browse` fails which is because the options aren't used in Pest here:
https://github.com/pestphp/pest/blob/master/src/Laravel/Commands/PestDuskCommand.php#L39

We could maybe change this, but it would require basically the same changes as are in the referenced PR.

**Comment by pristavu** [comment]
Sorry for the missing informations. Indeed, in a fresh install of pest on a laravel app the command pest:dusk fails from missing option "--browse" that was introduced in version 6 of laravel/dusk
