### ISSUE TITLE
Integration of Pest and CodeIgniter

### ISSUE THREAD

**Issue by takumade** [pestphp/pest#313]
Hello this is not an issue, but does anyone know how i can integrate Pest and CodeIgniter, I badly want to introduce testing in my work flow

**Comment by owenvoke** [comment]
I don't personally use CodeIgniter, and haven't for the last 7~ years, so I'm probably not going to be much help.

I'd assume that it would be mostly similar to [the PHPUnit test documentation for CodeIgniter](https://codeigniter.com/user_guide/testing/overview.html). However, rather than having classes that have the required testing traits, you'd instead use Pest's `uses()` calls. Such as:

```php
use CodeIgniter\Test\ControllerTestTrait;
use CodeIgniter\Test\CIUnitTestCase;
use CodeIgniter\Test\DatabaseTestTrait;

uses(CIUnitTestCase::class, ControllerTestTrait::class, DatabaseTestTrait::class);

it('checks that categories are shown', function () {
    $result = $this->withURI('http://example.com/categories')
                   ->controller(\App\Controllers\ForumController::class)
                   ->execute('showCategories');

    expect($result->isOK())->toBeTrue();
});
```

It looks like you can also provide custom configuration, either by having `tests` entries in config files such as your `app/Config/Database.php`, or providing an `Config\App` instance in your tests.

```php
$config = new Config\App();
$config->appTimezone = 'Europe/London';

beforeEach(fn() => $this->withConfig($config));
```

---

If anyone else has experience with CodeIgniter and Pest, then feel free to chip in or correct me. 👍🏻
