### ISSUE TITLE
Coverage is not working in GitLab CI

### ISSUE THREAD

**Issue by bigint** [pestphp/pest#315]
Code Coverage is failing in GitLab CI

![image](https://user-images.githubusercontent.com/69431456/121891558-3884f680-cd39-11eb-9fed-1a0e35f183e6.png)

But this is working fine in Mac M1

![image](https://user-images.githubusercontent.com/69431456/121891690-68cc9500-cd39-11eb-9d8e-fad9ab99eed3.png)

Here is the CI URL https://gitlab.com/taskord/taskord/-/jobs/1344627134

**Comment by owenvoke** [comment]
Do you happen to be using Xdebug 3 in your CI workflow? This seems to look like Pest is throwing an exception (probably related to not finding the Coverage driver), and then Laravel's error handler is catching this for some reason and trying to send off the exception.

To rule out whether this is an issue with `--coverage`, do you mind trying to run it without the `--coverage` flag and see if it passes? If it does, we can assume this is due to a driver issue, etc.

Also note that Pest has a known caveat with Xdebug 3, which is noted [in the Coverage docs](https://pestphp.com/docs/coverage#overview). Is the `XDEBUG_MODE` environment variable set to include `coverage`? 👍🏻
