### ISSUE TITLE
Support for PHPUnit @covers notation

### ISSUE THREAD

**Issue by Joucke** [pestphp/pest#32]
PHPUnit supports coverage [annotations](https://phpunit.readthedocs.io/en/9.1/annotations.html), both test class wide and per test.

```
/**
 * @test 
 * @covers App\Model
 */

```

This will limit coverage calculation to only this class (or method, if specified, etc). 

Is it possible to do this in Pest?

**Comment by owenvoke** [comment]
This would be quite interesting to have with methods for `covers(... $class)` and `coversNothing()`.

I've taken a quick look and I'm not sure if this could be implemented in a similar way to the [`group()` call](https://github.com/pestphp/pest/blob/master/src/PendingObjects/TestCall.php#L81).

We may be able to look at [this method in PHPUnit](https://github.com/sebastianbergmann/phpunit/blob/3da2ced818c857826dbb800ca963ff3dc7f7ea9b/src/Util/Test.php#L540) for more information.

**Comment by nunomaduro** [comment]
@Joucke Can you try to develop this? Should be just adding something like this: https://github.com/pestphp/pest/pull/103/files#diff-4726f6affac796013ea01b71b2a6aae7R90.

**Comment by Joucke** [comment]
Sorry, I've been looking at this - but I really don't understand how either pest or phpunit work internally. Thought it'd be a nice challenge, but I have no idea where to start.

**Comment by DannyvdSluijs** [comment]
If this remains untouched I could take a stab at this somewhere in the near future. No promises though.
It seems only some glueing between Pest and the PHPUnit internals are needed. No need to mimic the annotations itself, right?

**Comment by owenvoke** [comment]
@DannyvdSluijs, yep. I tried to get the 2 working together and passing the classes to PHPUnit, but hit a few issues which I didn't have time to overcome. 😬 Good luck if you do have a go, that'd be great!

**Comment by DannyvdSluijs** [comment]
PHPUnit handles the `@covers` differently then a `@depends`. As with an `@depend` the meta data is set on the `Testcase` which was quite easily made possible in Pest as hinted by @nunomaduro. But the test coverage is part of the  `Testresult` class which is [invoking](https://github.com/sebastianbergmann/phpunit/blob/master/src/Framework/TestResult.php#L843) the `PHPUnit\Util::getLinesToBeCovered()` directly as a static function in its `run` method. This has the effect that in its current form phpunit is wired to only support PHP DocBlock annotations on the test class and method, something which would not work for Pest.

It seems in order to support which parts of the code it is supposed to tested in Pest we would need to overload the `TestResult::run` method which, with its 330 lines is quite a large method to overload. With all the risk that will come with it such as upkeep, backwards compatibility challenges etc.

Perhaps this shows why this task hasn't been resolved since some time. Perhaps even some issue needs to be raised with some PR in order to allow PHPUnit for a more easier override of the cover coverage collection. But I'm unsure if this is going to be a successful path to follow it will be a timely path for sure.

**Comment by nunomaduro** [comment]
I've no plans of adding this myself. Fell free to submit a pull request with this.

**Comment by bolechen** [comment]
+1 for @covers support.

**Comment by danilopolani** [comment]
@nunomaduro I noticed that Pest v2 is ready to support annotations when building the test method:

https://github.com/pestphp/pest/blob/04663e0c8e046fafaa7006ea9f6803623e1833e0/src/Factories/TestCaseMethodFactory.php#L137-L145

With this change it should be easy to implement `@covers`, right? Additionally PHPUnit 10 now *prefers* (I guess? Currently it accepts both attributes and annotations) [PHP Attributes for coverage](https://github.com/sebastianbergmann/phpunit/blob/2235d219922f3c320a12180f0a0094b14d40e875/tests/_files/Metadata/Attribute/tests/CoversTest.php#L17-L20):

<img width="331" alt="immagine" src="https://user-images.githubusercontent.com/6277291/156578236-2fc770ae-73aa-4f56-bba0-0b56f89b663a.png">

I was trying to play with it to *maybe* submit a PR, but with PHPUnit 10 the `--coverage` flag does not work anymore to me (with XDebug 3.1) 🤕
