### ISSUE TITLE
Shared setup/teardown not working

### ISSUE THREAD

**Issue by bpolaszek** [pestphp/pest#337]
Hello there,

I have an app which currently runs Pest 1.8 with hundreds of tests. I just wanted to use the "Reusable (Shared) Setup and Teardown" feature by writing this on top of my `tests/Pest.php` file:

```php
uses()->in('Unit')->beforeEach(fn () => dump('Hi'));
```

Then when running `./vendor/bin/pest` again here's what I immediately get:

> Fatal error: Uncaught Pest\Exceptions\InvalidPestCommand: Please run `./vendor/bin/pest` instead of `/vendor/bin/phpunit`. in ./vendor/pestphp/pest/src/TestSuite.php:114

Since it's a private project, I can't share it with you, so I tried to reproduce it here from a fresh [Symfony skeleton](https://github.com/bpolaszek/pest-shared-setup). It doesn't work either, but [for a different reason](https://github.com/bpolaszek/pest-shared-setup/runs/2997158955?check_suite_focus=true#step:5:7):

> Call to a member function beforeEach() on null

And, indeed, after investigating, it looks like [`UsesCall::in()`](https://github.com/pestphp/pest/blob/master/src/PendingObjects/UsesCall.php#L73) returns `void`.

So I don't really understand how this feature is supposed to work...

Thanks!
Ben

**Comment by jordanbrauer** [comment]
Hello, @bpolaszek ! :)

My apologies for any issues you are having with this (I implemented it 😅 )! I hope it's not too much of a blocker.

Based on your example there, it seems to me there might be an order of operations issue. [Take a look at **the test**](https://github.com/pestphp/pest/blob/master/tests/Pest.php#L7-L20), and you can see that `in` is called last, as you have already discovered it returns nothing! It can be thought of/read as "do something **_in_** here", rather than "do **_in_** here, something".

Hopefully that helps!

**Comment by bpolaszek** [comment]
Hey @jordanbrauer - sorry I was sure I answered and it happened I didn't 😓 
Thank you for the tip, will give it a try! Maybe it would be good to update the docs or make it fluent?

Thanks!
Ben
