### ISSUE TITLE
[PHP 7.3] Error in symfony/console/Output/ConsoleOutput.php on line 33

### ISSUE THREAD

**Issue by Sairahcaz** [pestphp/pest#605]
Hi,

on the installation page [here](https://pestphp.com/docs/installation) it says PHP 7.3 is supported.
I have php7.3 but when running pest, I get this error:

```
PHP Parse error:  syntax error, unexpected 'array' (T_ARRAY), expecting function (T_FUNCTION) or const (T_CONST) in /.../vendor/symfony/console/Output/ConsoleOutput.php on line 33
```

**Comment by owenvoke** [comment]
From the output you've provided, it looks like that's an issue with Symfony Console using a syntax that isn't supported (rather than an issue with Pest). Could you post your version of Pest and Symfony Console?

And could you also confirm you aren't ignoring platform requirements with `--ignore-platform-reqs`? 🙂 The syntax change which is being shown (at least without any further details) looks like the changes in Symfony Console 6.0, which requires PHP 8.0 or later.

**Comment by Sairahcaz** [comment]
@owenvoke thanks!  `platform-check` was set to `false` on this project. I missed that. Now it's working!

**Comment by Sairahcaz** [comment]
@owenvoke thanks!  `platform-check` was set to `false` on this project. I missed that. Now it's working!
