### ISSUE TITLE
Cannot find tests in "Helpers" directory

### ISSUE THREAD

**Issue by MichaelRushton** [pestphp/pest#734]
Using v2.2.2.

If the directory name of the tests is "tests/Helpers" then it cannot find any tests. See the attached screenshots, where tests are found if the directory name is "tests/Helper" but not found if the directory name is "test/Helpers".

It works as expected if it's "tests/subdirectory/Helpers".

<img width="656" alt="Screenshot 2023-03-24 080246" src="https://user-images.githubusercontent.com/49325097/227461090-28b368e5-f67d-434b-8db9-ed88f3dda03d.png">
<img width="657" alt="Screenshot 2023-03-24 080340" src="https://user-images.githubusercontent.com/49325097/227461102-192633ae-c748-4fac-9644-7bd6b9939344.png">

**Comment by owenvoke** [comment]
As far as I know, this is expected. I think helper functions are automatically extracted from the top-level `Helpers` directory.

It doesn't look like the directory-style structure is documented though.
https://pestphp.com/docs/custom-helpers

**Comment by gehrisandro** [comment]
After upgrading from v1 to v2 I run into the exact same problem. 

It worked perfectly fine with v1 but with v2 all tests in the "Helpers" directory are silently ignored. I only realized it because I tried to execute a specific test in the Helpers directory some days later.

Maybe we could add some information into the upgrade guide.

If you agree I can make a PR.
