### ISSUE TITLE
Dusk v7.8.0 breaks pest:dusk command

### ISSUE THREAD

**Issue by Roboroads** [pestphp/pest#857]
As title sais. Getting the following errorwhen running on 7.8.0 of Dusk.

> The "pest" option does not exist.

**Comment by owenvoke** [comment]
This is a Dusk issue afaik, [this line](https://github.com/laravel/dusk/pull/1038/files#diff-df6c8a539f0feb30220c5c46ecdd475f054d4bb2cc4ff6f69c247ef8d2512a35R165) should really check that the `--pest` option exists as well (with `$this->hasOption('pest')`). 🤔

The `pest:dusk` command doesn't have that option, because it's intended for Pest (so doesn't really make sense). 🤷🏻
https://github.com/pestphp/pest-plugin-laravel/blob/2.x/src/Commands/PestDuskCommand.php#L19
