### ISSUE TITLE
[Bug]: `expect()->extend()` does not work with `$this->and()`

### ISSUE THREAD

**Issue by mnapoli** [pestphp/pest#944]
### What Happened

`expect()->extend()` does not seem to behave correctly when returning `$this->and()`.

The code below was inspired from the `->json()` expectation.

### How to Reproduce

```php
expect()->extend('base64', function () {
    return $this->and(base64_decode($this->value));
});

test('test', function () {
    expect('dGVzdA==')->base64()->toBe('test');
});
```

Output:

```diff
 FAILED  Tests\Feature\TestTest > test
Failed asserting that two strings are identical.
-'test'
+'dGVzdA=='
```

### Pest Version

2.16.0

### PHP Version

8.2

### Operation System

macOS

**Comment by devajmeireles** [comment]
Hey, @mnapoli . Thanks for your report.

I'll check it out.

**Comment by devajmeireles** [comment]
@mnapoli , Thanks for your report.

Behind the scenes, when we are dealing with `and` method we are creating a new expectation instance, so it rewrites the current `$this->value`, that's why your testing is failing.

A very useful and simple alternative to that is making something like this:

```diff
expect()->extend('base64', function () {
-    return $this->and(base64_decode($this->value));
+    return $this->and($this->value = base64_decode($this->value));
});
```

Or, even more simple:

```diff
expect()->extend('base64', function () {
-    return $this->and(base64_decode($this->value));
+    return $this->value = base64_decode($this->value);
});
```

In none of the examples above do we rewrite the current instance of Expectation, but only by changing the current value.

**Comment by mnapoli** [comment]
Thanks a lot for the workaround! I actually based my code on the `->json()` implementation, so it might be handled differently.

I'll do what you suggest, thanks! Not sure if it's worth adding to the docs, but as another OS maintainer I don't want to impose the burden of this onto you so I'll close this 😂

Thanks!

**Comment by devajmeireles** [comment]
> 

No problem. I will doc this.
