### ISSUE TITLE
[Bug]: `--update-snapshots` ignores `--filter`

### ISSUE THREAD

**Issue by jaulz** [pestphp/pest#958]
### What Happened

When I use the `--filter` option I would expect that the `--update-snapshots` command will only be applied to the tests scoped by the filter.

### How to Reproduce

1. Install a fresh Laravel app
2. Add Pest
3. Create two test files (FirstTest and SecondTest) with a test using `expect([ 'random' => rand() ])->toMatchSnapshot();`
4. Run tests to create initial snapshots
5. Run tests with `--filter First --update-snapshots` -> expectation would be that only the FirstTest's snapshot is updated but in reality only the FirstTest's snapshot is updated and the rest is deleted

### Pest Version

2.18.0

### PHP Version

8.1.20

### Operation System

Linux

**Comment by nunomaduro** [comment]
No plans to make this those flags compatible.

**Comment by Ken-vdE** [comment]
> No plans to make this those flags compatible.

@nunomaduro What? That's incredibly counter-intuitive. You sure that's not a feature you want to implement?
How else would you update snapshots of a single test, instead of all tests?
And why would all other snapshots be deleted? That's even worse.

Also, see https://github.com/pestphp/pest/issues/1395
